mitodl/smoot-design

.github/workflows/release.yml, .github/workflows/validate-pr.yml, .releaserc.json, README.md, package.json, yarn.lock
For https://github.com/mitodl/hq/issues/6039
This PR adds [semantic-release](https://semantic-release.gitbook.io/semantic-release) to release this package. It:
- inspects commits since last release to construct changelog +  decide next version number (major/minor/patch)
- only commits using conventional commit are included
- Since we usually squash commits, this repo is set to use PR title as default squashed commit message, and we enforce conventional commit PR titles.
- publishes the release to NPM and github releases page
1. Read the [readme](https://github.com/mitodl/smoot-design/blob/e862c05eeef83eb996124c485c96e99ac9a6cefd/README.md). It should make sense.
2. View the "Release" section of https://github.com/mitodl/smoot-design/actions/runs/11846407719/job/33013978096 to see example …
=> chore: Add release action

.npmrc
Attempting to fix broken release action: https://github.com/mitodl/smoot-design/actions/runs/11955738538
When a scoped (`@mitodl/package-name`) package is first published to NPM, it defaults to private. Our account can't publish private packages (nor do we care to).
This sets the `--access public` flag in npmrc.
Run `npm config get access` in this directory.
=> fix: specify npm package is public

src/components/Button/ActionButton.stories.tsx, src/components/Button/Button.tsx, src/components/ThemeProvider/ThemeProvider.stories.tsx, src/components/ThemeProvider/ThemeProvider.tsx
Better explain theme customization.
=> docs: explain theme customization more

.eslintrc.js, .storybook/main.ts, README.md, package.json, src/components/Button/ActionButton.stories.tsx, src/components/Button/ActionButton.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/LinkAdapter/LinkAdapter.tsx, src/components/ThemeProvider/ThemeProvider.stories.tsx, src/components/ThemeProvider/Typography.stories.tsx, src/index.ts, src/story-utils/index.ts
None, but did this as a separate PR on the way to https://github.com/mitodl/hq/issues/6192
This switches Storybook's autodocs to use `react-docgen-typescript`, as described [here](https://storybook.js.org/docs/configure/integration/typescript#the-types-are-not-being-generated-for-my-component)
Why:
- `react-docgen` wasn't worked with styled components / emotion. This appears to be a [known, old issue](https://github.com/reactjs/react-docgen/issues/256) with `react-docgen`. 
- `react-docgen-typescript` handles enums automatically for us, and other types, too.
1. Read the updated readme
2. Run `yarn storybook --docs` locally.
3. View http://localhost:6006/?path=/docs/smoot-design-button--docs ; the docs should look good and http://localhost:6006/?path=/docs/smoot-design-actionbutton--docs …
=> docs: Use `react-docgen-typescript` for autodoc generation

src/components/Button/ActionButton.stories.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
For https://github.com/mitodl/hq/issues/6279
Adds the "bordered" button variant, introduced in MIT Learn in https://github.com/mitodl/mit-learn/pull/1900
With the repo set up (just `yarn install`)
1. Run `yarn start` to start storybook.
2. View the new bordered button variant
- http://localhost:6006/?path=/docs/smoot-design-button--docs
- http://localhost:6006/?path=/docs/smoot-design-actionbutton--docs
3. ☝️ should look the same as the "bordered" variant at https://mitodl.github.io/mit-learn/?path=/story/smoot-design-button--variant-story
=> feat: add bordered variant for buttons

README.md, package.json, src/components/ThemeProvider/ThemeProvider.tsx, src/components/ThemeProvider/breakpoints.ts, src/components/ThemeProvider/typography.ts, src/index.ts, src/type-augmentation/theme.d.ts, yarn.lock
A tweak for https://github.com/mitodl/hq/issues/6279
This PR:
- makes mui peer dependencies instead of regular dep. Making a peer dependency removes possibility for multiple versions, which (A) bloats and (B) can be problematic for `useContext`. 
- deep merges theme opt into the defaults, for reason mentioned HERE
Test with this branch in MIT Learn:
- https://github.com/mitodl/mit-learn/pull/1979
This is a breaking change. (Though in practice, I'm not sure any of our repos will require an update to accomodate for this.)
=> fix!: make mui, emotion peer deps

src/components/Button/ActionButton.stories.tsx, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
None, but followup to #40 since that was a breaking change anyway.
Removes the `unstable_` button variants, which were erroneously introduced in MIT Learn.
Tests should pass; if you want, `yarn start` and check out the Button page.
Note: This branch is in use on https://github.com/mitodl/mit-learn/pull/1979
=> feat!: remove unstable variants

src/components/AiChat/AiChat.tsx
Followup to #44 
Fixes an image issue in NextJS
Regular image (storybook)
NextJS image tag:
We don't have a great way to test this at the moment in isolation. Smoot-design's storybook doesn't use NextJS right now (intentionally).
This can be tested on https://github.com/mitodl/mit-learn/pull/1999, which is using this branch right now.
=> fix: image aspect ratio in AiChat

src/components/AiChat/AiChat.stories.tsx, src/components/AiChat/AiChat.tsx, src/components/AiChat/test-utils/api.ts, src/components/Input/Input.tsx
https://github.com/mitodl/hq/issues/6815
- Applies the design updates in the linked issue that relate to the chat component.
- Provides a container for the AiChat input and disclaimer with classname for selecting in calling components.
`yarn start` and navigate to http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs
- The chat input should be styled according to [Figma](https://www.figma.com/design/Eux3guSenAFVvNHGi1Y9Wm/MIT-Design-System?node-id=16926-56822&t=65uU7nSD9tpEPcrh-0) on hover. The disabled state on the send adornment is removed on feedback that it should not look disabled on first load. Hover styles are also applied when focused. 
- Updated padding on \<ol\> and \<ul\> lists rendered from markdown chat messages. Change includes a mock message with nested lists (send …
=> feat: AiChat UI changes

bundle-preview/bundle-demo.html, bundle-preview/iframe.html, src/bundles/RemoteAiChatDrawer/RemoteAiChatDrawer.tsx
https://github.com/mitodl/hq/issues/6843
This PR adds a `requestBody` to the `remoteAiChatDrawer` message events, as used in https://github.com/mitodl/open-edx-plugins/pull/447
1. Run `yarn bundle-preview`.
2. Visit http://localhost:3000/bundle-demo
3. Enter something into the input field and click "Open Drawer"
4. Send a message to the AI while looking at network tab of browser dev tools.
5. Observe the extra data sent in request body is the input tab value, set via `requestBody` in `bundle-preview/iframe.html`
=> feat: add requestBody to message events 

package.json, src/bundles/RemoteAiChatDrawer/RemoteAiChatDrawer.tsx, src/bundles/remoteAiChatDrawer.tsx, yarn.lock
Closes https://github.com/mitodl/hq/issues/6827
This PR does two things:
1. Makes the drawer a bit wider, 900px on wide screens instead of 600px
2. Isolates the styles by putting the app root in a shadow DOM.
1. Run `yarn bundle-preview` locally
2. Navigate to http://localhost:3000/bundle-demo and click "Open Drawer".
- The drawer should open
- If you inspect the DOM, you should see that the model and its contents are inside a shadow root.
=> feat: remoteAiChatDrawer style updates

.pre-commit-config.yaml, bundle-preview/bundle-demo.html, bundle-preview/iframe.html, src/bundles/RemoteAiChatDrawer/RemoteAiChatDrawer.tsx
Closes https://github.com/mitodl/hq/issues/6855
This PR makes the openedx chat drawer—`remoteAiChatDrawer`—include credentials (cookies) in its fetch requests by default. This is for maintaining conversation state between requests.
1. **Easy Option:** Run `yarn bundle-preview` and visit the bundle preview at http://localhost:3000/bundle-demo Then:
- Open the chat drawer
- make some chat requests.
- Inspect your local cookies (or network requests) and see that the API requests tried to set some cookies but they were rejected because localhost:3000 and api-learn-ai-qa.ol.mit.edu are not the same site. (SameSite cookies won't work).
- But at least you saw they were trying to set the cookies. It will work on RC, since `mitxonline.mit.edu` and api-learn-ai-qa.ol.mit.edu` are the same site …
=> feat: include credentials by default in remoteAiChatDrawer

src/components/AiChat/AiChat.tsx, src/components/AiChat/types.ts
Relates to https://github.com/mitodl/hq/issues/6815
In certain contexts the scrolling and snap behavior will be handled by a parent component and not the messages container. One option is to provide an `onMessageSubmit` callback; this option just provides a prop to pass the scroll container element.
=> feat: Prop to provide a scroll element

.storybook/preview.tsx
None
This PR fixes the deployed storybook github pages, which is currently broken. See https://mitodl.github.io/smoot-design/?path=/docs/smoot-design-button--docs
1. If you want to see it broken locally, run `rm -rf deployed && mkdir -p deployed && yarn build-storybook && mv storybook-static deployed/subpath` on main branch and visit http://localhost:3000/subpath/?path=/docs/smoot-design-button--docs
2. Repeat on this branch.
=> fix: use relative path for msw

src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.stories.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx
Relates to https://github.com/mitodl/hq/issues/6985
We were not able to set a title for the RemoteTutorDrawer and were using the AiChat component's title for the drawer title. This worked fine before we added tabs, though we can't sensibly reuse the AiChat title across tabs.
This change provides `title` on the `postMessage()` payload for opening the drawer.
Titles starting with "AskTIM" are given the <img width="59" alt="image" src="https://github.com/user-attachments/assets/4df23af8-a06a-4af2-b4aa-f778e9751300" /> treatment.
Start Storybook with `yarn start` and navigate to http://localhost:6006/?path=/docs/smoot-design-ai-remotetutordrawer--docs. Hi the open drawer buttons and confirm the titles display as expected and layout is preserved, with attention to long chat threads.
=> feat: Title for tutor drawer

src/bundles/RemoteTutorDrawer/FlashcardsScreen.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx
N/A
Following https://github.com/mitodl/smoot-design/pull/75, removes the flashcards tab if none are returned from the API, averting the subsequent bug trying to display them.
1. Run `yarn start` and visit http://localhost:6006/?path=/docs/smoot-design-ai-remotetutordrawer--docs
2. Edit the storybook file to return an empty array of flashcards 
3. Open the video drawer and check that the flashcard tab is not present.
=> fix: Remove the flashcards tab if none

src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.stories.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx, src/components/AiChat/AiChat.tsx, src/components/AiChat/EntryScreen.tsx
https://github.com/mitodl/hq/issues/7010
Displays the chat entry screen by default for the Tutor drawer, when opened on a video block.
- Provides the option to override the default `entryScreenEnabled`
- Selects 3 starter messages from the returned flashcard questions where none provided, or uses hardcoded defaults.
- Padding adjustments and mobile breakpoints.
Run `yarn start` and load http://localhost:6006/?path=/docs/smoot-design-ai-remotetutordrawer--docs.
Open the drawer in the Video Story and check that layout is preserved, conversation starters are correctly set and the chat screen is preserved between tab navigation.
Minor breaking change for release:
- The AiChat no longer uses the `entryScreenTitle` as initial assistant message by default.
Notes for upgrade on OpenEdx Plugin:
- …
=> feat: Chat entry screen for the Tutor drawer

.github/workflows/release.yml, .releaserc.json
Closes https://github.com/mitodl/hq/issues/7053
Switches the semantic-release github token to the [automatic token created for github actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret) rather than the personal token tied to my account (!)
1. View https://github.com/mitodl/smoot-design/actions/runs/14314603143/job/40117702828,  this is a run of the release action using `--dry-run` (first commit on this branch) that verifies permissions.
=> fix: use automatic token during release

src/components/TabButtons/TabButtonList.tsx, src/index.ts
For https://github.com/mitodl/hq/issues/7090
In a previous PR, we added Tab-related components https://github.com/mitodl/smoot-design/pull/67 for use inside chat. This PR publishes them.
Note: These are the same tabs used inside MIT Learn today, so the learn ones could be replaced with these now. (In https://github.com/mitodl/smoot-design/pull/67 an optional variant was added, but the default is the Learn tabs.)
See https://mitodl.github.io/smoot-design/?path=/docs/smoot-design-tabbuttons--docs
=> feat: publish our customized tab components

src/components/AiChat/AiChat.tsx, src/components/AiChat/EntryScreen.tsx, src/components/Input/Input.tsx
In part addresses: https://github.com/mitodl/hq/issues/7082
<br />
To test, in http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs, in the first story showing the entry screen:
- enter a prompt
- click a conversation starter button
The message input should be focused and accepting keyboard input for both cases.
<br />
To test, in http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs, in the first story showing the entry screen:
- Tab through the conversation starter buttons. 
They should receive tab focus in the order they appear. Hitting enter on a focused button should submit the prompt.
<br />
To test, in http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs, in the first story showing the entry screen. Using a screen reader (cmd+F5 for VoiceOver if you're …
=> fix: Accessibility issues

src/components/AiChat/AiChat.stories.tsx, src/components/AiChat/AiChat.tsx
Small fix.
Removes the double indentation for \<ol\> elements in chat. It was intended to accommodate longer lists with numbers that  overflow to the left, but looks incorrect where we have unordered lists nested within ordered lists.
Run `yarn start`
There's a story with some list variations at http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs#markdown-styling-3
=> fix: Remove double indent for chat message ordered lists

.github/workflows/ci.yml, package.json, src/components/AiChat/AiChat.tsx, src/components/AiChat/utils.ts, tsconfig.json, yarn.lock
Followup to https://github.com/mitodl/smoot-design/pull/29 because `yarn build` is currently broken on `main`.
This PR:
1. Switches us back to `moduleResolution: "node"` from "bundler", which produces an error during `yarn build`.
```
tsconfig.json:7:25 - error TS5095: Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.
7     "moduleResolution": "bundler",
~~~~~~~~~
````
2. And resolves the type errors encountered in https://github.com/mitodl/smoot-design/pull/29 by using `@ai-sdk/react`.
3. Also adds `yarn build` on CI, which would have caught this issue.
`yarn build` should succeed, and everything should work like before.
=> fix: Use ai-sdk instead of ai directly

src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.stories.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.test.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx
https://github.com/mitodl/hq/issues/7191
Adds default initial chat messages for the Problem drawer.
Run Storybook (`yarn start`) and visit http://localhost:6006/?path=/docs/smoot-design-ai-remotetutordrawer--docs#problem-default-initial-messages-story. This story demonstrates a problem drawer with no initial messages provided. The default assistant message should be shown: "Let's try to work on this problem together. It would be great to hear how you're thinking about solving it. Can you walk me through the approach you're considering?"
=> feat: Default initial chat messages for problem drawer

.gemini/config.yaml
None
Makes gemini optional (by request)
=> chore: make gemini optional

jest.config.ts, package.json, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.stories.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.test.tsx, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx, src/bundles/remoteTutorDrawer.tsx, src/components/AiChat/AiChat.stories.tsx, src/components/AiChat/AiChat.tsx, src/components/AiChat/Markdown.tsx, src/components/AiChat/test-utils/api.ts, src/components/AiChat/types.ts, yarn.lock
closes https://github.com/mitodl/hq/issues/7108
adds an optional useMathJax param to the AiChat object to use MathJax to display chat messages
Go to 
http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs 
and verify that mathjax is displayed in the markdown
Follow the steps in 
https://github.com/mitodl/learn-ai/pull/168
=> feat: rehype mathjax

package.json, src/components/AiChat/AiChat.mdx, src/components/AiChat/AiChatContext.tsx, src/components/AiChat/types.ts, src/utils/retryingFetch.test.ts, src/utils/retryingFetch.ts, yarn.lock
Closes https://github.com/mitodl/hq/issues/7238
This PR enables retries on failed AiChat requests. Requests are retried 3 times with exponential backoff, 1s, 2s, 4s.
The easiest way to test this is illustrated in the screenshot above:
1. `yarn start` and navigate to http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs
2. Open network tab.
3. Pick an AiChat story and chat with it.
4. In network tab, block the chat requests—this will force them to fail and is an easy way to cause network errors.
5. Send another message. You should see it fail, then see it retried 3 times.
=> feat: retry failed aichat requests

bundle-preview/iframe.html, scripts/build.sh, scripts/set_version.js, src/VERSION.ts, src/bundles/RemoteTutorDrawer/RemoteTutorDrawer.tsx, src/index.ts, vite.config.mts
None (Things I worked on while debugging https://github.com/mitodl/hq/issues/7259)
This PR:
1. Updates the bundle preview HTML 
2. adds sourcemaps to the `remoteTutorDrawer` bundle
3. embeds `VERSION` in the library code.
1. **Bundle-preview updates:** With [learn-ai](https://github.com/mitodl/learn-ai) running locally with default settings, run `yarn bundle-preview` and navigate to http://localhost:3000/bundle-demo ... The drawer should work. You can test problem/video drawer by clicking the "Set drawer data.." buttons. You can edit the textarea data.
2. Continuing (1), you should be able to see raw source in your browser via sourcemaps, e.g., in Chrome the "Sources" tab:
3. You can test the version embedding by noting that https://unpkg.com/@mitodl/smoot-design@0.0.0-1967631/dist/esm/VER …
=> chore: Improve bundle debugging

src/bundles/remoteTutorDrawer.tsx
Fixes https://github.com/mitodl/hq/issues/7306
We were rendering the drawer component into the shadow DOM to ensure that styles are isolated, though this impacts focus management as browsers do not reliably traverse the traverse into the shadow root causing our accessibility fixes to ensure that the chat input is focused and that tabs, flashcards and other elements are navigable by keyboard to not work as intended.
As styles are no longer scoped to the shadow root, this may have the unintended consequence that page styles are applied to the drawer and that the Smoot Design styles impact the page.
This is best tested therefore in the context of an actual application. This can be done by loading an MITx Online page that has a video block, e.g. …
=> fix: Remove drawer rendering into shadow DOM

src/components/AiChat/AiChat.tsx
https://github.com/mitodl/hq/issues/7260
We don't want to display the entry screen to a user that is returning to an existing chat session, however once the AiChat is freshly mounted, the entry screen is always shown if enabled.
This change checks if there are user messages in the chat history or if the chat is in progress and will not show the entry screen.
This is best tested on the Learn site - the smoot-design AiDrawer now keeps the drawer mounted and this issue is specifically around returning to a drawer once unmounted.
Over on mit-learn:
- Install the preview package: `yarn up @mitodl/smoot-design@0.0.0-9776b48`
- Open the learning resource drawer on a course.
- Open AskTIM and submit a prompt.
- Close the slidedown and drawer.
- Open the learning resource drawer on the same …
=> fix: Hide the entry screen if there are user messages

scripts/build.sh
RemoteTutorDrawer was renamed to AiDrawerManager in https://github.com/mitodl/smoot-design/pull/116, also renaming the bundle output files. A Vite build config was added to produce the legacy filenames for backwards compatibility, however the package script call was missing from the build script. This adds it in.
- Run `yarn build`
- Confirm that ./dist/bundles/remoteTutorDrawer.es.js is produced.
=> fix: Add legacy to build script

src/components/AiChat/AiChat.tsx
- Closes https://github.com/mitodl/hq/issues/8182
The canvas tutor agent endpoint (https://api.rc.learn.mit.edu/ai/http/demo_canvas_tutor_agent/) will reject prompts unless accompanied by a `problem_set_title`.
This PR disables prompt submit until the user has made a selection from the assignment dropdown.
- Run `yarn start` to fire up Storybook.
- Navigate to the assignment selection preview at http://localhost:6006/?path=/docs/smoot-design-ai-aichat--docs#assignment-selection.
- Ensure that the send button is disabled and that you are not able to submit a prompt by click it or by hitting enter.
- Select a problem set from the assignment dropdown. Ensure that you are now able to submit a prompt.
=> fix: Disable prompt submit if problem set not selected

.yarnrc.yml
_This PR was generated automatically via a script._
This PR disables yarn's postinstall scripts by setting `enableScripts: false` in `.yarnrc.yml`. It is part of:
- https://github.com/mitodl/hq/issues/8676
Disabling postinstall scripts improves security by:
- **Preventing malicious code execution**: Stops potentially harmful scripts from running during package installation
- **Supply chain security**: Reduces risk from compromised packages that could execute malicious postinstall scripts
- **Controlled execution**: Allows manual review and execution of necessary scripts only when needed
- Added `enableScripts: false` to `.yarnrc.yml`
- Some packages may require manual script execution if they depend on postinstall hooks
- Improved security posture against supply chain attacks
- No …
=> fix: [Security] Disable yarn postinstall scripts

src/bundles/AiDrawer/AiDrawerManager.tsx, src/components/AiChat/AiChat.test.tsx, src/components/AiChat/AiChat.tsx, src/components/AiChat/AiChatMarkdown.stories.tsx, src/components/AiChat/Markdown.tsx, src/components/AiChat/test-utils/api.ts, src/components/AiChat/types.ts, src/utils/string.ts
Fixes: https://github.com/mitodl/hq/issues/8694
**Preloads the \boldsymbol MathJax/TeX extension to ensure it is available when rendered.**
There is a race condition around the load timing of the boldsymbol extension script and the render.
1. better-react-mathjax loads the base MathJax on load - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
2. The chat endpoint responds with math that includes \boldsymbol (assuming here that there is no use of \boldsymbol in initial messages - the problem doesn't present when included in first render).
3. The MathJax script loads the boldsymbol extension script on demand when encountered - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/input/tex/extensions/boldsymbol.js
4. Depending on response time, /boldsymbol is …
=> fix: Math \boldsymbol is not rendered

src/components/AiChat/AiChat.test.tsx, src/components/AiChat/AiChat.tsx, src/components/AiChat/AiChatContext.stories.tsx, src/components/AiChat/AiChatContext.tsx, src/components/AiChat/test-utils/api.ts, src/components/AiChat/types.ts, src/components/AiChat/utils.ts, src/components/Tooltip/Tooltip.tsx, src/index.ts
Frontend for https://github.com/mitodl/hq/issues/8382
- Adds like/dislike buttons for assistant responses.
- Extracts the `thread_id` and `checkpoint_pk` from comments in assistant responses (needed for the Learn AI feedback endpoint).
- Calls the Learn AI endpoint on feedback selection.
- By default is the `apiUrl` origin and [`/ai/api/v0/chat_sessions/:threadId/messages/:checkpointPk/rate/`](https://github.com/mitodl/learn-ai/blob/main/openapi/specs/v0.yaml#L127).
- A `feedbackApiUrl` prop is added to override this. Our use case is that for Open edX instances, the request needs to be forwarded via LMS/CMS endpoints provided by the plugin (new endpoint to be created alongside [ol_chat](https://github.com/mitodl/open-edx-plugins/blob/main/src/ol_openedx_chat_xblock/ol_openedx_chat_xblock/b …
=> feat: Chat feedback buttons
